Repository RaceOnProject/RaceOn-Server, pull requests merged in 2025-03, with the labels that each got.

#148 [Docs] 웹 소켓 문서 작성(에러 구독과 변경된 destination반영)
  src/docs/asciidoc/games/process-games.adoc
  src/docs/asciidoc/games/reject-game.adoc
  src/docs/asciidoc/games/start-games.adoc
  src/docs/asciidoc/games/stop-games.adoc
  src/docs/asciidoc/socket/socket.adoc
Labels: documentation

#150 [Fix] boolean 변수 직렬화 오류 해결("is" prefix 붙여서 반환되도록 수정)
  src/main/java/com/parting/dippin/api/game/dto/socket/GameProcessResDto.java
  src/main/java/com/parting/dippin/api/game/dto/socket/GameStartResDto.java
  src/main/java/com/parting/dippin/api/game/dto/socket/GameStopResDto.java
Labels: bug

#152 [Refactor] FCM 데이터에 title, message 추가
  src/docs/asciidoc/fcm/fcm.adoc
  src/main/java/com/parting/dippin/core/common/fcm/FcmMessenger.java
Labels: refactor

#146 [Feat] 게임이 시작되지 않은 경우, 게임 최대 시간이 초과된 경우 스케줄러 처리
  src/main/java/com/parting/dippin/core/scheduler/ConnectionStatusScheduler.java
  src/main/java/com/parting/dippin/core/scheduler/GameSchedulerService.java
  src/main/java/com/parting/dippin/core/scheduler/GameTerminatorScheduler.java
  src/main/java/com/parting/dippin/entity/game/GameEntity.java
  src/main/java/com/parting/dippin/entity/game/enums/ProgressStatus.java
  src/main/java/com/parting/dippin/entity/game/repository/GameRepository.java
Labels: enhancement

#154 [Feat] Websocket ExceptionHandler에 로깅 추가
  src/main/java/com/parting/dippin/core/exception/WebsocketExceptionHandler.java
Labels: enhancement

#155 Refactor/logging
  src/main/java/com/parting/dippin/core/exception/WebsocketExceptionHandler.java
Labels: bug
